name: Code Quality
run-name: ${{ github.actor }} has committed new code! 🚀 Checking...

on: [push, pull_request]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i cognitive-complexity-ts
      - run: npx ccts-json ./src
      - run: REACT_APP_COMMIT_SHA=$CF_PAGES_COMMIT_SHA REACT_APP_VERSION=$npm_package_version react-app-rewired build
